services:
  frontend:
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - "0.0.0.0:80:8080"
    environment:
      NODE_ENV: production

  backend:
    environment:
      NODE_ENV: production

