services:
  frontend:
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - "127.0.0.1:80:3000"
    environment:
      NODE_ENV: production

  backend:
    environment:
      NODE_ENV: production

